
module.exports = [
    'r-release',
    'r-oldrel',
    'r-oldrel/1',
    'r-oldrel/2',
    'r-oldrel/3',
    'r-oldrel/4',
    'r-oldrel/5',
    'r-oldrel/6',
    'r-oldrel/7',
    'r-oldrel/8',
    'r-oldrel/9',
    'r-oldrel/10',
    'r-versions',
    'r-release-tarball',
    'r-release-win',
    'r-release-macos',
    'r-next',
    'r-next-win',
    'r-next-macos',
    'r-prerelease',
    'r-prerelease-win',
    'r-prerelease-macos'
];
